export const Colors = {
    Blond: '#FEEEC2',
    SunGlow: '#FFC933',
    Jasmine: '#FFDE82',
    PastelOrange: '#FCBF3F',
    White: '#FEFEFE',
    OuterSpace: '#444444',
    Kiwi: '#76E250',
    Mustard: '#FDD156',
    Mustard2: '#FFE15D',
    AntiFlashWhite: '#F2F2F2',
    Gainsboro: '#DADADA',
    TeaGreen: '#C7EBD1',
    SpanishViridian: '#077D55',
    PalePink: '#FADCD9',
    MaximumRed: '#D91F11',
    AzureishWhite: '#D4E4FA',
    BrightNavyBlue: '#186ADE',
    DeepLemon: '#F5C518',
    LightGoldenrodYellow: '#FAF6CF',
    Gray: '#BBBBBB',
    ChineseSilver: '#CBCBCB',
    ChineseWhite: '#E0E0E0',
    SpanishGray: '#999999',
    Manatee_02: '#959da533'
}